### PR TITLE
Remove Artifactory from README.md and pom.xml

### PR DESCRIPTION
**Pull request by Krenair**

### CODE REVIEW

**Comment by adityapahuja** [comment]
splunk-library-javalogging still needs to be published to JFrog artifactory because verify-hub downloads this library from the artifactory when VERIFY_USE_PUBLIC_BINARIES is set to false.

Source: https://github.com/alphagov/verify-hub/blob/a223f336053594554f3e98df23862e10d5f526a0/build.gradle#L176

**Comment by Krenair** [comment]
no, it just needs to publish to bintray to be able to download it via artifactory

**Review by blairboy362 — APPROVED** [review]

**Comment by blairboy362** [comment]
I thought we'd got rid of artifactory in favour of bintray...?

**Comment by Krenair** [comment]
Nope, we have a different Artifactory now.

**Review by chrisfarms — APPROVED** [review]

**Pull request merged**
